### ISSUE TITLE
Remove .DS_Store file

### ISSUE THREAD

**Issue by Wellidontcare** [richardvogg/interaction-labelling-tool#3]
Hi Richard,

I am kind of abusing this issue for a quick message.

I saw your presentation at the science slam, where you showed how you solved the problem of detecting the animals and the boxes. I got curious how you'd approach the issue of inferring the animal interactions. I see now that you are doing a direct labelling approach. 

Have you thought about doing pose estimation first and then training the model on the reduced data? (That would not work if the facial expression and the tail movement plays a crucial role)

Btw, you should maybe remove those .DS_Store files, as they are not relevant for Windows or Linux users.

Good luck with your thesis!

**Comment by richardvogg** [comment]
Thanks for reaching out! Yes, we are trying to label interactions directly and train scene graphs with it. We reviewed relevant methods recently in this preprint (https://arxiv.org/abs/2401.16424, section 2.4 and mostly appendix).
In this paper we also argue (section 4, intermediate representations) that we prefer the bounding box representation compared to pose, as it is very time consuming to label enough keypoints to get a model that generalizes well in in-the-wild-settings. For lab applications and human pose estimation it looks different, because of the low background complexity and the huge amount of available labelled data respectively.
If we had a good keypoint model, it would definitely be an interesting path to follow. Thanks for the suggestions and again for reaching out! :)

**Comment by Wellidontcare** [comment]
Thanks for the link to the preprint. I will check up on your (co-)authored publications from time to time :*)
